version: "2.2"
# https://docs.docker.com/compose/compose-file/compose-file-v2/

services:

    kipa:
        hostname: kipa
        container_name: kipa
        build: ./
        restart: on-failure
        expose:
            - "80"
        ports:
            - "80:80"
        healthcheck:
            test: ["CMD", "curl", "-f", "http://127.0.0.1/kipa/"]
            interval: 30s
            timeout: 10s
            retries: 5
        logging:
            driver: json-file
            options:
                max-size: "5m"
                max-file: "10"
        
        
            